export default function handler(req, res) {
  const levels = [
    "Kyouki",
    "Calibrate",
    "Haunted Ship",
    "VSC",
    "KOCMOC UNLEASHED",
    "Heliopolis",
    "Grief",
    "Goober Rage Stage",
    "Nullscapes",
    "Cant Let Go",
    "Fingerdash V3",
    "iSpyWithMyLittleEye",
    "Skeletan Shenanigans",
    "B",
    "BOOBAWAMBA",
    "Sakupen Joy",
    "GLUNGUS ADVENTURES",
    "FOREST OF SPIKES",
    "Bloom",
    "Rust",
    "In This",
    "Ordinary",
    "Society",
    "Thinking Space II",
    "Amethyst",
    "Flamewall",
    "Quanteuse Processing",
    "The Bloop",
    "GREFG",
    "How two platformer",
    "The Tower XXII",
    "XO",
    "Future Funk III",
    "Tsunami",
    "Hi",
    "auto play area",
    "dorabaebasic4",
    "Worlds Smallest Viol",
    "Biden Circles",
    "Trump Circles",
    "thespikeisoverthere",
    "Kenos",
    "Gronos",
    "Danklocked",
    "My Bae",
    "Explorerers",
    "Element 111 Rg",
    "Slaugherhouse",
    "Maniacal Chains",
    "Sakupen Circles",
    "rauchkammer",
    "Codependence",
    "WHAT",
    "HOW",
    "Death Corridor",
    "Eon",
    "PP",
    "GGEZ",
    "Dark Dimension",
    "Nervhell",
    "Frigid Thrills",
    "Orochi",
    "Dissipation",
    "Ascension of Heaven",
    "Vehemence",
    "Love Baba",
    "Congregation",
    "Mountain King",
    "Press Start Full Version",
    "too kiD frIEndly",
    "Peaceful",
    "Player vs Creator",
    "MikuMikuMikuMiku",
    "Forbidden",
    "Lethal Lava Land",
    "Saul Goodman"
  ];

  const creators = [
    "Demishio",
    "awesomeme360",
    "Bamvie",
    "neigefeu",
    "SirGuillester",
    "Dorami",
    "Jax",
    "Riot",
    "Zobros",
    "KrmaL",
    "Voxicat",
    "DORABAE",
    "Serponge",
    "Bli",
    "IcEDCave",
    "OniLinkGD",
    "ViPriN",
    "Mindcap",
    "BoBoBoBoBoBoBo",
    "saRy",
    "CairoX",
    "APTeamOfficial",
    "cherryteam",
    "TheShadowRealm",
    "Renn241",
    "Presta",
    "BIANOX",
    "OddMod",
    "ItzKiba",
    "PockeWindfish",
    "Darwin",
    "Danzmen",
    "lTemp",
    "Rob Buck",
    "Robtop",
    "Pennutoh",
    "Stormfly",
    "Spu7nix",
    "para",
    "Akunakunn",
    "nikroplayz",
    "Knobbelboy",
    "MadisonYuko",
    "JonathanGD",
    "nick24",
    "Manix648",
    "TeamN2",
    "thejshadow",
    "vortrox",
    "TheRealSailent",
    "Neomarbilan",
    "Zafkiel7",
    "f4lixsram",
    "tricipital",
    "Lemons",
    "Split72",
    "Mulpan"
  ];

  const randomLevel = levels[Math.floor(Math.random() * levels.length)];
  const randomCreator = creators[Math.floor(Math.random() * creators.length)];

  res.setHeader("Content-Type", "text/plain");
  res.status(200).send(`${randomLevel} by ${randomCreator}`);
}
